micronaut:
  application:
    name: learningProject
  http:
    server:
      cors:
        enabled: true
datasources:
  default:
    url: ${MYSQL_URL}/minishop?createDatabaseIfNotExist=true&characterEncoding=UTF-8
    username: root
    password: test1234
    dialect: MYSQL
    driverClassName: com.mysql.cj.jdbc.Driver
    schema-generate: none
endpoints:
  flyway:
    enabled: true
    sensitive: false
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
flyway:
  datasources:
    default:
      enabled: true
      clean-schema: false
      locations: classpath:db/migration

